apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  name: kw-test-storage-bucket
spec:
  location: ASIA
  uniformBUcketLevelAccess: true
  lifecycleRule:
  - action:
      type: Delete
    condition:
      age: 7