name: run-tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read
  pull-requests: read

jobs:
  run-tests-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run-tests 
        run: |
          make verify-gator
