name: run-tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read
  pull-requests: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: "Verify assertions"
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - run: |
          make verify-gator